import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen mx-auto">
          <div className="w-[70%] mx-auto flex flex-col gap-12">
            <Navbar />
            {children}</div>
        </div>
      </body>
    </html>
  );
}
